### ISSUE TITLE
Need clarification on ID generation and usage

### ISSUE THREAD

**Issue by attwad** [outbreakprepared/mvp-notes-and-ideas#21]
There seems to be a few IDs throughout

  - spreadsheet ID in CONFIG file (`ID = 000` for example)
  - ID column (first column in all spreadsheets)
  - admin_id (last column in all spreadsheets)

Thomas can you please answer those questions:
- can they change between runs? aka. must a row in the sheet always keep its original ID?
- who is using them?
- do they have to follow a special format or can they be made random? (incremental vs uuid for example)

Thanks!

**Comment by tbrewer-healthmap** [comment]
Hey, 

The IDs are suppose to be static, and sequential as we add them to the sheet. 
When we started we only had 1 sheet, so no XXX- or anything like that. But when we started splitting we wanted to be able to differentiate between the sheets so we started adding the prefixes.

For the Private Sheet (original), they do not appear there but we tagged on 000-1 for outside_Hubei, and 000-2- for "Hubei", but that only gets done when generating the CSV.  
For the others we have : 

001 - Africa
002 - Asia/Oceania
003 - Europe
004 - LATAM
005 - North America
006 - NYC.  

The ID in the config files is only used to append those prefixes. 

The admin-id I believe is a key attached to a specific location, and gets looked up in the geo_admin sheet (could also be done externally). 

To answer the questions : 
- can they change between runs? aka. must a row in the sheet always keep its original ID?
A row is suppose to keep the original ID, that way we ca

- who is using them?
The cleaning script uses them to get the number of rows in a few places, but it also inserts them depending on the length of the "country" column... So I guess they aren't that useful for that.  I think curators use them to reference entries that might need to be updated.  

- do they have to follow a special format or can they be made random? (incremental vs uuid for example)
I was told to ensure that they are sequential.  But frankly,  I don't think it matters as long as they are always the same.

**Comment by BernardoGG** [comment]
To chime in here, Thomas' reply covers most of the ID column information. They were meant to be used for tracking purposes (i.e. going back to them to update data or information, particularly in the outcome column) but I can't say they've been too practical for that purpose. Once case counts increase there's little chance to back-track individual cases from most National reporting systems.

**Comment by attwad** [comment]
Thanks for the clarifications both that was very useful!

Adding serial IDs is the only write action that's left from the cleanup script, I'd really love to be able to make that script readonly on sheets to avoid conflicts and slow operations (update cells has a mean latency of 3s and 99%ile of 15s (!!)).
If we can keep the existing IDs, keep the same output format in CSV and do the "generate new IDs" in the script that generates the CSV would you be okay with that?
If new rows are reorganized in the sheet then that might break but I think the benefits outweigh the costs here.

WDYT?

**Comment by tbrewer-healthmap** [comment]
I'm closing this since we talked about it a bit yesterday, but to recap : yes let's do that!

**Comment by attwad** [comment]
Ok I'll file a new issue to track the work that needs to be done. Turns out Monday is also a holiday so I can work on that on Tuesday.
