### ISSUE TITLE
North America sheet geocoding info only has input column

### ISSUE THREAD

**Issue by attwad** [outbreakprepared/mvp-notes-and-ideas#26]
https://docs.google.com/spreadsheets/d/1gvYnjXkyhI_8FEJ5IpSiPr4cvCxQzw5w6J8uEti7UH4/edit#gid=1292752263

It doesn't have any geocode/admin1/admin2 etc

Thomas what should be done here?

**Comment by tbrewer-healthmap** [comment]
Hey, I think it does have the the columns.  The formatting is weird though, you can only scroll on the last shown column ( after the I column).  But it is there

**Comment by attwad** [comment]
Oh yeah you're right somehow I didn't see those this morning... too many tabs open :p
