### ISSUE TITLE
New spreadsheet script should copy the SOP sheet as well

### ISSUE THREAD

**Issue by attwad** [outbreakprepared/mvp-notes-and-ideas#58]
I don't think that's happening, we should be consistent and copy it as well.

**Comment by tbrewer-healthmap** [comment]
I believe it does already 
https://docs.google.com/spreadsheets/d/1s8xGRYCbgRdZnSkUglD7DVzKBieUC_LgpePHFSX6jbY/

If we're seeing different things, maybe its a permissions issue?

**Comment by attwad** [comment]
I don't have permission to see that spreadsheet, can you share it with me? I also trust you if you say it is copied :)

**Comment by tbrewer-healthmap** [comment]
I just shared anyways... But yeah its there
