### ISSUE TITLE
Move back the sheet_cleanup code to the beoutbreakprepared/nCoV2019 repo

### ISSUE THREAD

**Issue by attwad** [outbreakprepared/mvp-notes-and-ideas#59]
I'm not sure if it's worth keeping this repository if what it's solely doing is building stuff for that other repo.
The others are building their projects in another repo under open-covid-data so I propose that we migrate the code back to beoutbreakprepared/nCoV2019, sounds good?

**Comment by tbrewer-healthmap** [comment]
sure sounds good, I've moved things back there!

**Comment by attwad** [comment]
Please move the github action workflow as well so that tests are run on pull requests, that's definitely a nice thing to have.

**Comment by attwad** [comment]
https://github.com/open-covid-data/mvp-notes-and-ideas/tree/master/.github/workflows

**Comment by attwad** [comment]
The SOP link in the spreadsheets also need to be moved to the repo's link.
