### ISSUE TITLE
wuhan(0)_not_wuhan(1) in geo_admin sheet seems wrong

### ISSUE THREAD

**Issue by attwad** [outbreakprepared/mvp-notes-and-ideas#6]
At least on the Europe sheet I'd expect everything to be set to 1 but some rows are empty, there are no zeroes but even "Wuhan City;Hubei;China" is set to 1...
Same apparently even for the china sheets, should we get rid of that column altogether?

**Comment by tbrewer-healthmap** [comment]
I think it is safe to drop.  The column was present in the original sheets, but we decided to drop it when we started making new ones, this lead to  inconsistencies and patch work in the script to handle the different formats (both in the data and the geo_admin references).  I think it would be good to have a single format throughout the sheets.

**Comment by attwad** [comment]
Thanks Thomas, we don't have edit rights on the sheets yet.
Should we get write access?

**Comment by iamleeg** [comment]
merge this with #10?

**Comment by attwad** [comment]
Indeed let's drop this in favor of #10 .
